---
Name: remoteassetsync
After: 'framework/routes#coreroutes'
---
Director:
    rules:
        'remoteassetlist' : 'RemoteAssetListController'
        'remoteassetdiff' : 'RemoteAssetDiffController'
        'remoteassetdownload' : 'RemoteASsetDownloadController'
